
spring:
  datasource:
    url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:172.16.3.180}:${DATASOURCE_PORT:3306}/sc_auth?characterEncoding=UTF-8mb4&useUnicode=true&useSSL=false&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:root123}
  security:
    oauth2:
      jwt:
        signingKey: 123456
  application:
    name: authorization-server
  mvc:
    throw-exception-if-no-handler-found: true

logging:
  level:
    org.springframework.web: debug
    org.springframework.security: DEBUG
    org.apache.ibatis: debug
    java.sql.PreparedStatement: debug
  path: logs/
  file:
    max-size: 1GB
management:
  endpoints:
    web:
      exposure:
        include: '*'

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8000
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_ZONE_HOST:localhost}:${EUREKA_ZONE_PORT:8761}/eureka/
